var queue,validated=[],flagged=[],skipped=[],deleted=[],history=[];
var overrides=JSON.parse(localStorage.getItem('ogx_editor_overrides')||'{}');
var deletedData=JSON.parse(localStorage.getItem('ogx_deleted')||'[]');
deleted=deletedData;
var activeRules=RULES.filter(function(r){return deleted.findIndex(function(d){return d.sym===r.sym;})===-1;});
function shuffle(a){for(var i=a.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1));var t=a[i];a[i]=a[j];a[j]=t;}}
function restart(){activeRules=RULES.filter(function(r){return deleted.findIndex(function(d){return d.sym===r.sym;})===-1;});queue=activeRules.map(function(r){return Object.assign({},r);});shuffle(queue);validated=[];flagged=[];skipped=[];history=[];document.getElementById('total-count').textContent=TOTAL;render();}
restart();
function getCat(c){return CAT[c]||CAT["💧 Water"];}
function getOverrides(sym){var o=overrides[sym]||{};var r=RULES.find(function(r){return r.sym===sym;});var d=getCat(r?r.cat:'💧 Water');return {note:o.note||null,pros:o.pros||d.pros,cons:o.cons||d.cons,info:o.info||d.info};}
function render(){
  var done=validated.length+deleted.length;
  document.getElementById('done-count').textContent=done;
  document.getElementById('total-count').textContent=TOTAL;
  document.getElementById('progress').style.width=((done/TOTAL)*100)+'%';
  if(queue.length===0){
    document.getElementById('card-area').innerHTML='<div class="done-screen"><h2>🎉 All Reviewed!</h2><div class="big-num">'+TOTAL+'</div><p style="color:var(--muted);">💧'+WC+' water · ⚡'+EC+' elec · 🌱'+FC+' food</p><div class="stat-row"><div class="stat-box"><div class="num" style="color:var(--emerald);">'+validated.length+'</div><div class="label">Validated</div></div><div class="stat-box"><div class="num" style="color:var(--amber);">'+flagged.length+'</div><div class="label">Flagged</div></div><div class="stat-box"><div class="num" style="color:var(--muted);">'+skipped.length+'</div><div class="label">Skipped</div></div><div class="stat-box"><div class="num" style="color:var(--rose);">'+deleted.length+'</div><div class="label">Deleted</div></div></div>'+(flagged.length?'<details><summary>⚠ Flagged ('+flagged.length+')</summary>'+flagged.map(function(r){return '<div style="font-size:.42rem;margin:1px 0;color:var(--amber);">⚠ '+r.sym+' — $'+r.price+' — '+r.cat+'</div>';}).join('')+'</details>':'')+(deleted.length?'<details><summary>🗑️ Deleted ('+deleted.length+')</summary>'+deleted.map(function(d){return '<div style="font-size:.42rem;margin:1px 0;color:var(--rose);">🗑️ '+d.sym+' — '+d.cat+'</div>';}).join('')+'</details>':'')+'<div style="margin-top:.5rem;font-size:.42rem;color:var(--muted);">'+Object.keys(overrides).length+' custom edits saved</div><button class="btn-restart" onclick="restart()">🔄 Review Again</button> <button class="btn-export" onclick="exportData()">📥 Export All</button>'+(deleted.length?' <button class="btn-restore" onclick="restoreDeleted()">♻️ Restore Deleted</button>':'')+'</div>';return;}
  var r=queue[0],cd=getCat(r.cat),ov=getOverrides(r.sym);
  var priceDisplay=r.price===0?'—':'$'+r.price;
  var noteText=ov.note||r.note;
  var h='<div class="card">';
  h+='<div class="card-header"><span class="card-symbol">'+r.sym+'</span><div class="card-price-block"><div class="card-price">'+priceDisplay+'</div><div class="card-range">'+r.range+' '+r.unit+'</div></div></div>';
  h+='<div class="badges"><span class="badge badge-'+r.conf+'">'+r.conf+'</span>'+(r.safety?'<span class="badge badge-safety">SAFETY</span>':'')+'<span class="badge badge-cat">'+r.cat+'</span></div>';
  h+='<div class="note-edit editable" id="note-edit" contenteditable="true">'+noteText+'</div>';
  h+='<div class="pros-cons">';
  h+='<div class="pc-box pc-pros"><span class="pc-label">PROS ✓</span><div class="editable" id="pros-edit" contenteditable="true">'+ov.pros+'</div></div>';
  h+='<div class="pc-box pc-cons"><span class="pc-label">CONS ✗</span><div class="editable" id="cons-edit" contenteditable="true">'+ov.cons+'</div></div>';
  h+='</div>';
  h+='<div class="actions">';
  h+='<button class="btn btn-save" onclick="saveAndNext()">💾 Save & Next</button>';
  h+='<button class="btn btn-delete" onclick="saveAll();doDelete()">🗑️ Delete</button>';
  h+='<button class="btn btn-grok" onclick="openGrok()">🔍 Grok</button>';
  h+='<button class="btn btn-flag" onclick="saveAll();doFlag()">⚠ Flag</button>';
  h+='<button class="btn btn-skip" onclick="saveAll();doSkip()">↓ Skip</button>';
  h+='<button class="btn btn-help" onclick="saveAll();showHelp()">? Info</button>';
  h+='<button class="btn btn-validate" onclick="saveAll();doValidate()">✓ Validate</button>';
  h+='</div></div>';
  document.getElementById('card-area').innerHTML=h;}
function saveAll(){if(queue.length===0)return;var sym=queue[0].sym,noteEl=document.getElementById('note-edit'),prosEl=document.getElementById('pros-edit'),consEl=document.getElementById('cons-edit');if(!overrides[sym])overrides[sym]={};if(noteEl)overrides[sym].note=noteEl.innerText;if(prosEl)overrides[sym].pros=prosEl.innerText;if(consEl)overrides[sym].cons=consEl.innerText;Object.keys(overrides[sym]).forEach(function(k){if(!overrides[sym][k])delete overrides[sym][k];});if(Object.keys(overrides[sym]).length===0)delete overrides[sym];localStorage.setItem('ogx_editor_overrides',JSON.stringify(overrides));}
function saveAndNext(){saveAll();if(queue.length===0)return;var r=queue.shift();skipped.push(r);history.push({action:'skip',rule:r});render();}
function doDelete(){if(queue.length===0)return;var r=queue.shift();deleted.push(r);localStorage.setItem('ogx_deleted',JSON.stringify(deleted));history.push({action:'delete',rule:r});render();}
function openGrok(){if(queue.length===0)return;var r=queue[0];var q=encodeURIComponent('off-grid '+r.sym.replace(/_/g,' ')+' '+r.cat.replace('💧 ','water ').replace('⚡ ','electricity ').replace('🌱 ','food ')+' guide pricing specs');window.open('https://grok.com/?q='+q,'_blank');}
function showHelp(){if(queue.length===0)return;var r=queue[0],cd=getCat(r.cat),ov=getOverrides(r.sym);var h='<button class="close-btn" onclick="closeHelp()">✕</button><h3>'+r.sym+'</h3>';h+='<div class="badges" style="margin-bottom:.4rem;"><span class="badge badge-'+r.conf+'">'+r.conf+'</span><span class="badge badge-cat">'+r.cat+'</span><span style="font-size:.48rem;font-weight:bold;">'+(r.price===0?'Reference':'$'+r.price+' '+r.unit)+'</span>'+(r.safety?'<span class="badge badge-safety">SAFETY</span>':'')+'</div>';h+='<h4 style="color:var(--cyan);">📝 Full Note</h4><div class="note-edit editable" id="info-note-edit" contenteditable="true" style="margin-bottom:.4rem;">'+(ov.note||r.fullNote||r.note)+'</div>';h+='<h4 style="color:var(--emerald);">PROS</h4><div class="pc-box pc-pros editable" id="info-pros-edit" contenteditable="true">'+ov.pros+'</div>';h+='<h4 style="color:var(--amber);">CONS</h4><div class="pc-box pc-cons editable" id="info-cons-edit" contenteditable="true">'+ov.cons+'</div>';h+='<h4 style="color:var(--violet);">DETAILS / INFO</h4><div class="info-edit editable" id="info-edit" contenteditable="true">'+ov.info+'</div>';h+='<div style="text-align:center;margin-top:.5rem;"><button class="btn btn-save" onclick="savePopupAll();closeHelp()">💾 Save All & Close</button></div>';document.getElementById('popup').innerHTML=h;document.getElementById('overlay').classList.add('active');}
function savePopupAll(){if(queue.length===0)return;var sym=queue[0];if(!overrides[sym])overrides[sym]={};var n=document.getElementById('info-note-edit'),p=document.getElementById('info-pros-edit'),c=document.getElementById('info-cons-edit'),i=document.getElementById('info-edit');if(n&&n.innerText!==(queue[0].fullNote||queue[0].note))overrides[sym].note=n.innerText;if(p)overrides[sym].pros=p.innerText;if(c)overrides[sym].cons=c.innerText;if(i)overrides[sym].info=i.innerText;Object.keys(overrides[sym]).forEach(function(k){if(!overrides[sym][k])delete overrides[sym][k];});if(Object.keys(overrides[sym]).length===0)delete overrides[sym];localStorage.setItem('ogx_editor_overrides',JSON.stringify(overrides));}
var syncUrl=localStorage.getItem('ogx_sync_url')||'http://192.168.0.17:8765';
function setSyncUrl(){var u=prompt('Sync server URL:',syncUrl);if(u){syncUrl=u;localStorage.setItem('ogx_sync_url',u);alert('Sync URL: '+u);}}
function syncToServer(){if(Object.keys(overrides).length===0&&deleted.length===0){alert('No edits to sync.');return;}var payload={overrides:overrides,deleted:deleted,source:'tablet',syncedAt:new Date().toISOString()};var el=document.createElement('div');el.style.cssText='position:fixed;bottom:1rem;right:1rem;background:var(--card);border:1px solid var(--cyan);color:var(--cyan);padding:.5rem 1rem;border-radius:8px;font-size:.55rem;z-index:9999;';el.textContent='📤 Syncing...';document.body.appendChild(el);fetch(syncUrl+'/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}).then(function(r){return r.json();}).then(function(d){el.textContent='✅ Synced! '+d.results.length+' changes';el.style.borderColor='var(--emerald)';el.style.color='var(--emerald)';setTimeout(function(){el.remove();},3000);}).catch(function(e){el.textContent='❌ Failed: '+e.message+'\nNeed same WiFi as server ('+syncUrl+')';el.style.borderColor='var(--rose)';el.style.color='var(--rose)';setTimeout(function(){el.remove();},5000);});}
function exportData(){var d={overrides:overrides,deleted:deleted,validated:validated.length,flagged:flagged.length,skipped:skipped.length,exportedAt:new Date().toISOString()};var b=new Blob([JSON.stringify(d,null,2)],{type:'application/json'});var a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='ogx-review-export.json';a.click();}
function restoreDeleted(){if(!confirm('Restore all '+deleted.length+' deleted cards?'))return;queue=queue.concat(deleted);deleted=[];localStorage.setItem('ogx_deleted','[]');shuffle(queue);render();}
function closeHelp(){savePopupAll();document.getElementById('overlay').classList.remove('active');}
document.getElementById('overlay').addEventListener('click',function(e){if(e.target===this)closeHelp();});
function doValidate(){if(queue.length===0)return;var r=queue.shift();validated.push(r);history.push({action:'validate',rule:r});render();}
function doFlag(){if(queue.length===0)return;var r=queue.shift();flagged.push(r);history.push({action:'flag',rule:r});render();}
function doSkip(){if(queue.length===0)return;var r=queue.shift();skipped.push(r);history.push({action:'skip',rule:r});render();}
function undo(){if(history.length===0)return;var last=history.pop();if(last.action==='delete'){var idx=deleted.findIndex(function(d){return d.sym===last.rule.sym;});if(idx!==-1){queue.unshift(deleted.splice(idx,1)[0]);localStorage.setItem('ogx_deleted',JSON.stringify(deleted));}}else if(last.action==='validate'){queue.unshift(validated.pop());}else if(last.action==='flag'){queue.unshift(flagged.pop());}else if(last.action==='skip'){queue.unshift(skipped.pop());}render();}
document.addEventListener('keydown',function(e){if(document.activeElement&&document.activeElement.isContentEditable)return;if(e.key==='ArrowRight'){e.preventDefault();doValidate();}else if(e.key==='ArrowLeft'){e.preventDefault();doFlag();}else if(e.key==='ArrowDown'){e.preventDefault();doSkip();}else if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();doDelete();}else if(e.key==='g'||e.key==='G'){e.preventDefault();openGrok();}else if(e.key==='?'&&!e.shiftKey){e.preventDefault();showHelp();}else if(e.key==='Escape'){closeHelp();}else if(e.key==='z'||e.key==='Z'){e.preventDefault();undo();}else if(e.key==='r'||e.key==='R'){e.preventDefault();restart();}});
